//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostRec.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\OnlineSoft\\PT2\\BonTsDemux\\BonTsDemux.exe")]
        public string BonTsDemuxPath {
            get {
                return ((string)(this["BonTsDemuxPath"]));
            }
            set {
                this["BonTsDemuxPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\OnlineSoft\\PT2\\ffmpeg\\bin\\ffmpeg.exe")]
        public string ffmpegPath {
            get {
                return ((string)(this["ffmpegPath"]));
            }
            set {
                this["ffmpegPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\OnlineSoft\\AviUtil\\otherfile\\lgd")]
        public string LogoDir {
            get {
                return ((string)(this["LogoDir"]));
            }
            set {
                this["LogoDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\OnlineSoft\\AviUtil\\otherfile\\avs2yuv\\avs2yuv.exe")]
        public string AVS2YUVPath {
            get {
                return ((string)(this["AVS2YUVPath"]));
            }
            set {
                this["AVS2YUVPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\OnlineSoft\\AviUtil\\otherfile\\logoGuillo\\m2v.vfp")]
        public string M2VVFPPath {
            get {
                return ((string)(this["M2VVFPPath"]));
            }
            set {
                this["M2VVFPPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\OnlineSoft\\AviUtil\\otherfile\\logoGuillo\\logoGuillo.exe")]
        public string LogoGuilloPath {
            get {
                return ((string)(this["LogoGuilloPath"]));
            }
            set {
                this["LogoGuilloPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\OnlineSoft\\AviUtil\\aviutl.exe")]
        public string AviutlPath {
            get {
                return ((string)(this["AviutlPath"]));
            }
            set {
                this["AviutlPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\OnlineSoft\\AviUtil\\otherfile\\txt\\filtertemplate.txt")]
        public string FilterTemplatePath {
            get {
                return ((string)(this["FilterTemplatePath"]));
            }
            set {
                this["FilterTemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\OnlineSoft\\AviUtil\\otherfile\\txt\\prefilter.txt")]
        public string PreFilterPath {
            get {
                return ((string)(this["PreFilterPath"]));
            }
            set {
                this["PreFilterPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\OnlineSoft\\AviUtil\\otherfile\\txt\\postfilterDelogo.txt")]
        public string PostFilterDelogoPath {
            get {
                return ((string)(this["PostFilterDelogoPath"]));
            }
            set {
                this["PostFilterDelogoPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\OnlineSoft\\AviUtil\\otherfile\\txt\\postfilterSize.txt")]
        public string PostFilterSizePath {
            get {
                return ((string)(this["PostFilterSizePath"]));
            }
            set {
                this["PostFilterSizePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\OnlineSoft\\AviUtil\\otherfile\\txt\\postfilterAnime.txt")]
        public string PostFilterAnimePath {
            get {
                return ((string)(this["PostFilterAnimePath"]));
            }
            set {
                this["PostFilterAnimePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Video\\Encoded")]
        public string OutputDir {
            get {
                return ((string)(this["OutputDir"]));
            }
            set {
                this["OutputDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\OnlineSoft\\AviUtil\\otherfile\\auc")]
        public string AUCDir {
            get {
                return ((string)(this["AUCDir"]));
            }
            set {
                this["AUCDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Video\\ConvertedTS")]
        public string ConvertedFilePath {
            get {
                return ((string)(this["ConvertedFilePath"]));
            }
            set {
                this["ConvertedFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%1 %2")]
        public string DefaultEncoderArgs {
            get {
                return ((string)(this["DefaultEncoderArgs"]));
            }
            set {
                this["DefaultEncoderArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultEncoderPath {
            get {
                return ((string)(this["DefaultEncoderPath"]));
            }
            set {
                this["DefaultEncoderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\postrec.log")]
        public string LogFileName {
            get {
                return ((string)(this["LogFileName"]));
            }
            set {
                this["LogFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S0ServicePath {
            get {
                return ((string)(this["S0ServicePath"]));
            }
            set {
                this["S0ServicePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string T0ServicePath {
            get {
                return ((string)(this["T0ServicePath"]));
            }
            set {
                this["T0ServicePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string AviutilProfileNum {
            get {
                return ((string)(this["AviutilProfileNum"]));
            }
            set {
                this["AviutilProfileNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string AviutilPlugoutNum {
            get {
                return ((string)(this["AviutilPlugoutNum"]));
            }
            set {
                this["AviutilPlugoutNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Video\\ErrorFile")]
        public string ErrorFilePath {
            get {
                return ((string)(this["ErrorFilePath"]));
            }
            set {
                this["ErrorFilePath"] = value;
            }
        }
    }
}
